<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="DeleteTest"
    errors="0" failures="1" hostname="" id="" package="DeleteTest" skipped="0"
    tests="1" time="10.58" timestamp="Mon, 05 Feb 2018 12:53:06 GMT">
  
    <testcase name="Delete a quote" classname="DeleteTest" time="10.58" assertions="2">

      <failure message="Expected element &lt;.quote:nth-child(0)&gt; to be present - element was not found">    at Object.Delete a quote (C:\Users\val\Documents\COURS\4e_annee\unit_tests\finalv2\test\tests\DeleteTest.js:13:15)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)</failure>

    
    </testcase>
  

  

  
  </testsuite>
</testsuites>
